### ISSUE TITLE
Reduce amount of actions needed to create a tasking

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/Website#12]
- Can the primary mission be set to training, when assigning flights on a training mission?
- Can Al Dahfra be set automaticly when hosting a training event? (or set once for all flights)

**Comment by hiSylvan** [comment]
First point is done. 

Second point is... Yes, we can do that for now, but it's a dirty fix, because 1. We hosts non-PG ATRM training events and 2. If our main training location changes, say if we redeploy our main training location to another map, this becomes invalid. But yeah, I'll set it as such for now and try to think of a better way of reducing the workload.
